name: Test Workflow
on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Test step
      run: |
        echo "Hello World"
        echo "Workflow is working!"